// Embeds schemas/ and fixtures/ into lib/src/generated/embedded.g.dart so Dart
// consumers (tests in kletso_core / kletso_flutter, the fake transport) get
// the fixtures without file IO, which also works on the web.
//
// Usage: dart run tool/embed.dart [--check]
import 'dart:convert';
import 'dart:io';

const int maxEmbedBytes = 64 * 1024;

void main(List<String> args) {
  final check = args.contains('--check');
  final root = Directory.current.path;
  final out = File('$root/lib/src/generated/embedded.g.dart');
  final schemas = <String, String>{};
  for (final f in Directory('$root/schemas').listSync().whereType<File>()) {
    if (!f.path.endsWith('.json')) continue;
    schemas[_name(f.path)] = _normalize(f.readAsStringSync());
  }
  final fixtures = <String, String>{};
  final skipped = <String>[];
  for (final f in Directory(
    '$root/fixtures',
  ).listSync(recursive: true).whereType<File>()) {
    if (!f.path.endsWith('.json')) continue;
    final rel = f.path.substring('$root/fixtures/'.length);
    final text = f.readAsStringSync();
    if (utf8.encode(text).length > maxEmbedBytes) {
      skipped.add(rel);
      continue;
    }
    fixtures[rel] = _normalize(text);
  }
  final sortedFixtures = fixtures.keys.toList()..sort();
  final b = StringBuffer()
    ..writeln('// GENERATED by tool/embed.dart from schemas/ and fixtures/.')
    ..writeln('// Do not edit; run `dart run tool/embed.dart`.')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln("import 'dart:convert';")
    ..writeln()
    ..writeln('/// The JSON Schemas of the protocol, as text.')
    ..writeln('abstract final class KletsoSchemas {');
  for (final key in schemas.keys.toList()..sort()) {
    final field = _field(key);
    b
      ..writeln('  /// `schemas/$key.json`.')
      ..writeln("  static const String $field = r'''${schemas[key]}''';")
      ..writeln();
  }
  b
    ..writeln('  /// Every schema by file stem.')
    ..writeln('  static const Map<String, String> all = <String, String>{')
    ..writeAll(
      (schemas.keys.toList()..sort()).map((k) => "    '$k': ${_field(k)},\n"),
    )
    ..writeln('  };')
    ..writeln()
    ..writeln('  /// Decodes the schema with the given file stem.')
    ..writeln(
      '  static Map<String, Object?> json(String stem) => jsonDecode(all[stem]!) as Map<String, Object?>;',
    )
    ..writeln('}')
    ..writeln()
    ..writeln(
      '/// The conformance fixtures, as text, keyed by their path under',
    )
    ..writeln(
      '/// `fixtures/`. Files over ${maxEmbedBytes ~/ 1024} KB are not embedded',
    )
    ..writeln('/// (see `KletsoFixtureGenerators`).')
    ..writeln('abstract final class KletsoFixtures {');
  for (final key in sortedFixtures) {
    final field = _fixtureField(key);
    b
      ..writeln('  /// `fixtures/$key`.')
      ..writeln("  static const String ${field}Text = r'''${fixtures[key]}''';")
      ..writeln()
      ..writeln('  /// `fixtures/$key`, decoded.')
      ..writeln('  static Object? get $field => jsonDecode(${field}Text);')
      ..writeln();
  }
  b
    ..writeln('  /// Every embedded fixture by path.')
    ..writeln('  static const Map<String, String> all = <String, String>{')
    ..writeAll(
      sortedFixtures.map((k) => "    '$k': ${_fixtureField(k)}Text,\n"),
    )
    ..writeln('  };')
    ..writeln()
    ..writeln('  /// Paths of the valid surface fixtures.')
    ..writeln('  static const List<String> validSurfaces = <String>[')
    ..writeAll(
      sortedFixtures
          .where((k) => k.startsWith('ui/valid/'))
          .map((k) => "    '$k',\n"),
    )
    ..writeln('  ];')
    ..writeln()
    ..writeln('  /// Paths of the hand-written invalid surface fixtures.')
    ..writeln('  static const List<String> invalidSurfaces = <String>[')
    ..writeAll(
      sortedFixtures
          .where(
            (k) => k.startsWith('ui/invalid/') && !k.endsWith('manifest.json'),
          )
          .map((k) => "    '$k',\n"),
    )
    ..writeln('  ];')
    ..writeln()
    ..writeln('  /// Fixture files that were too large to embed.')
    ..writeln('  static const List<String> notEmbedded = <String>[')
    ..writeAll((skipped..sort()).map((k) => "    '$k',\n"))
    ..writeln('  ];')
    ..writeln()
    ..writeln(
      '  /// Decodes the fixture at [path]; throws if it is not embedded.',
    )
    ..writeln('  static Object? json(String path) => jsonDecode(all[path]!);')
    ..writeln('}');
  final content = b.toString();
  if (check) {
    final tmp = File('${Directory.systemTemp.path}/kletso_embedded_check.dart')
      ..writeAsStringSync(content);
    Process.runSync('dart', ['format', tmp.path]);
    final formatted = tmp.readAsStringSync();
    tmp.deleteSync();
    if (!out.existsSync() || out.readAsStringSync() != formatted) {
      stderr.writeln(
        'embedded.g.dart is out of date; run dart run tool/embed.dart',
      );
      exitCode = 1;
      return;
    }
    stdout.writeln('embedded.g.dart up to date');
    return;
  }
  out.parent.createSync(recursive: true);
  out.writeAsStringSync(content);
  final fmt = Process.runSync('dart', ['format', out.path]);
  if (fmt.exitCode != 0) {
    stderr.writeln(fmt.stderr);
    exitCode = 1;
  }
  stdout.writeln(
    'embedded ${schemas.length} schemas, ${fixtures.length} fixtures'
    '${skipped.isEmpty ? '' : ', skipped ${skipped.join(', ')}'}',
  );
}

String _name(String path) {
  final base = path.split('/').last;
  return base.substring(0, base.length - '.json'.length);
}

/// `kletso.ui.v1` -> `ui`, `kletso.events.v1` -> `events`.
String _field(String stem) {
  final parts = stem.split('.');
  return parts.length >= 3 ? parts[1] : stem.replaceAll('.', '_');
}

/// `ui/valid/flight_card.json` -> `flightCard`; invalid ones get an
/// `invalid` prefix, events/realtime keep their folder as prefix.
String _fixtureField(String rel) {
  final parts = rel.substring(0, rel.length - '.json'.length).split('/');
  String camel(String s) {
    final words = s.split(RegExp('[_-]'));
    return words.first +
        words.skip(1).map((w) => w[0].toUpperCase() + w.substring(1)).join();
  }

  if (parts.first == 'ui' && parts[1] == 'valid') return camel(parts.last);
  if (parts.first == 'ui' && parts[1] == 'invalid') {
    final c = camel(parts.last);
    return 'invalid${c[0].toUpperCase()}${c.substring(1)}';
  }
  final c = camel(parts.last);
  return '${parts.first}${c[0].toUpperCase()}${c.substring(1)}';
}

/// Re-encodes the JSON compactly so embedded text is canonical.
String _normalize(String text) => jsonEncode(jsonDecode(text));
