// Generates lib/src/theme/kletso_tokens.g.dart from packages/design/tokens.json.
// Usage: dart run tool/gen_tokens.dart [--check]
import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  final check = args.contains('--check');
  final root = Directory.current.path;
  final tokensFile = File('$root/../design/tokens.json');
  final out = File('$root/lib/src/theme/kletso_tokens.g.dart');
  final tokens =
      jsonDecode(tokensFile.readAsStringSync()) as Map<String, Object?>;
  final color = tokens['color']! as Map<String, Object?>;
  final derived = color.remove('derived')! as Map<String, Object?>;
  final font = tokens['font']! as Map<String, Object?>;
  final scale = font['scale']! as Map<String, Object?>;
  final radius = tokens['radius']! as Map<String, Object?>;
  final spacing = (tokens['spacing']! as List).cast<int>();

  String colorConst(String name, String hex) =>
      '  /// `#${hex.substring(1).toUpperCase()}`.\n  static const Color $name = Color(0xFF${hex.substring(1).toUpperCase()});\n';

  final b = StringBuffer()
    ..writeln(
      '// GENERATED by tool/gen_tokens.dart from packages/design/tokens.json.',
    )
    ..writeln('// Do not edit; run `dart run tool/gen_tokens.dart`.')
    ..writeln()
    ..writeln("import 'package:flutter/painting.dart';")
    ..writeln()
    ..writeln(
      '/// Primitive Kletso design tokens (raw values). Widgets never use these',
    )
    ..writeln('/// directly; they read semantic roles from `KletsoTheme`.')
    ..writeln('abstract final class KletsoTokens {')
    ..writeln(
      '  // ---- colour --------------------------------------------------------------',
    );
  for (final e in color.entries) {
    b.write(colorConst(e.key, e.value! as String));
  }
  for (final e in derived.entries) {
    b.write(colorConst(e.key, e.value! as String));
  }
  b
    ..writeln()
    ..writeln(
      '  // ---- typography ----------------------------------------------------------',
    )
    ..writeln(
      "  /// Primary UI font family.\n  static const String fontFamily = '${font['family']}';",
    )
    ..writeln(
      "  /// Handwritten accent family (marketing only).\n  static const String fontFamilyHand = '${font['hand']}';",
    );
  for (final e in scale.entries) {
    final v = (e.value! as List).cast<int>();
    final name = e.key;
    final cap = name[0].toUpperCase() + name.substring(1);
    b
      ..writeln(
        '  /// Marketing scale `${e.key}`: ${v[0]}/${v[1]} weight ${v[2]}.',
      )
      ..writeln('  static const double font${cap}Size = ${v[0]};')
      ..writeln('  /// Line height of `${e.key}`.')
      ..writeln('  static const double font${cap}LineHeight = ${v[1]};')
      ..writeln('  /// Weight of `${e.key}`.')
      ..writeln(
        '  static const FontWeight font${cap}Weight = FontWeight.w${v[2]};',
      );
  }
  b
    ..writeln()
    ..writeln(
      '  // ---- radius --------------------------------------------------------------',
    );
  for (final e in radius.entries) {
    final cap = e.key[0].toUpperCase() + e.key.substring(1);
    b.writeln(
      '  /// Radius `${e.key}`.\n  static const double radius$cap = ${e.value};',
    );
  }
  b
    ..writeln()
    ..writeln(
      '  // ---- spacing -------------------------------------------------------------',
    )
    ..writeln('  /// Spacing steps in logical pixels.')
    ..writeln(
      '  static const List<double> spacing = <double>[${spacing.join(', ')}];',
    )
    ..writeln('  /// Max content width on large screens.')
    ..writeln('  static const double container = ${tokens['container']};')
    ..writeln('}');
  final content = b.toString();
  if (check) {
    final tmp = File('${Directory.systemTemp.path}/kletso_tokens_check.dart')
      ..writeAsStringSync(content);
    Process.runSync('dart', ['format', tmp.path]);
    final formatted = tmp.readAsStringSync();
    tmp.deleteSync();
    if (!out.existsSync() || out.readAsStringSync() != formatted) {
      stderr.writeln(
        'kletso_tokens.g.dart is out of date; run dart run tool/gen_tokens.dart',
      );
      exitCode = 1;
      return;
    }
    stdout.writeln('kletso_tokens.g.dart up to date');
    return;
  }
  out.writeAsStringSync(content);
  Process.runSync('dart', ['format', out.path]);
  stdout.writeln('wrote ${out.path}');
}
