// Generates lib/src/avatar/kletso_avatar_face.g.dart from
// packages/design/avatar.json (the mascot face contract, D81).
// Usage: dart run tool/gen_avatar.dart [--check]
import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  final check = args.contains('--check');
  final root = Directory.current.path;
  final avatarFile = File('$root/../design/avatar.json');
  final out = File('$root/lib/src/avatar/kletso_avatar_face.g.dart');
  final json =
      jsonDecode(avatarFile.readAsStringSync()) as Map<String, Object?>;

  final colors = Map<String, Object?>.of(
    json['colors']! as Map<String, Object?>,
  );
  final geometry = Map<String, Object?>.of(
    json['geometry']! as Map<String, Object?>,
  )..remove(r'$comment');
  final defaults = Map<String, Object?>.of(
    json['defaults']! as Map<String, Object?>,
  )..remove(r'$comment');
  final moods = Map<String, Object?>.of(json['moods']! as Map<String, Object?>);
  final idle = Map<String, Object?>.of(json['idle']! as Map<String, Object?>)
    ..remove(r'$comment');
  final transition = json['transition']! as Map<String, Object?>;
  final lipsync = Map<String, Object?>.of(
    json['lipsync']! as Map<String, Object?>,
  )..remove(r'$comment');
  final rules =
      (json['rules']! as Map<String, Object?>)['default']! as List<Object?>;

  // colors.json key -> generated const name.
  const colorNames = <String, String>{
    'body': 'bodyColor',
    'bodyHighlight': 'bodyHighlight',
    'bodyShadow': 'bodyShadow',
    'eye': 'eyeColor',
    'eyeGloss': 'eyeGloss',
    'mouth': 'mouthColor',
    'tongue': 'tongueColor',
    'teeth': 'teethColor',
    'blush': 'blushColor',
  };

  String hex(String v) => v.replaceFirst('#', '').toUpperCase();

  String dartLiteral(Object? value) => switch (value) {
    null => 'null',
    final bool b => '$b',
    final int i => '${i.toDouble()}',
    final double d => '$d',
    final String s => "'${s.replaceAll(r"\", r"\\").replaceAll("'", r"\'")}'",
    final List<Object?> list =>
      '<double>[${list.map((e) => dartLiteral((e! as num).toDouble())).join(', ')}]',
    _ => throw StateError('cannot encode avatar.json value: $value'),
  };

  String mapLiteral(Map<String, Object?> map) {
    final entries = map.entries
        .map((e) => "'${e.key}': ${dartLiteral(e.value)}")
        .join(', ');
    return '<String, Object?>{$entries}';
  }

  final b = StringBuffer()
    ..writeln(
      '// GENERATED by tool/gen_avatar.dart from packages/design/avatar.json.',
    )
    ..writeln('// Do not edit; run `dart run tool/gen_avatar.dart`.')
    ..writeln()
    ..writeln("import 'package:flutter/animation.dart' show Curve, Curves;")
    ..writeln("import 'package:flutter/painting.dart' show Color, Offset;")
    ..writeln()
    ..writeln(
      '/// Raw mascot face data parsed from `packages/design/avatar.json`\n'
      '/// (D81). [KletsoAvatarFaceParams.forMood] and\n'
      '/// [KletsoAvatarController] build on this; widgets never read it\n'
      '/// directly.',
    )
    ..writeln('abstract final class KletsoAvatarFaceData {')
    ..writeln(
      '  // ---- colours ---------------------------------------------------------',
    );
  for (final e in colors.entries) {
    final name = colorNames[e.key] ?? e.key;
    final h = hex(e.value! as String);
    b
      ..writeln('  /// `#$h` (`${e.key}` in avatar.json).')
      ..writeln('  static const Color $name = Color(0xFF$h);');
  }
  b
    ..writeln()
    ..writeln(
      '  // ---- geometry (face units; head = circle radius 1 at (0,0)) -----------',
    );
  for (final e in geometry.entries) {
    final v = e.value;
    if (v is List<Object?>) {
      final nums = v.map((e) => (e! as num).toDouble()).toList();
      b
        ..writeln('  /// `${e.key}` from avatar.json.')
        ..writeln(
          '  static const Offset ${e.key} = Offset(${nums[0]}, ${nums[1]});',
        );
    } else {
      b
        ..writeln('  /// `${e.key}` from avatar.json.')
        ..writeln(
          '  static const double ${e.key} = ${(v! as num).toDouble()};',
        );
    }
  }
  b
    ..writeln()
    ..writeln(
      '  // ---- defaults: the neutral baseline every mood overrides from ---------',
    )
    ..writeln('  /// `defaults` from avatar.json.')
    ..writeln(
      '  static const Map<String, Object?> defaults = ${mapLiteral(defaults)};',
    )
    ..writeln()
    ..writeln(
      '  // ---- moods: only the params each mood changes --------------------------',
    )
    ..writeln('  /// `moods` from avatar.json, keyed by the wire mood name.')
    ..writeln('  static const Map<String, Map<String, Object?>> moods =')
    ..writeln('      <String, Map<String, Object?>>{');
  for (final e in moods.entries) {
    b.writeln(
      "        '${e.key}': ${mapLiteral(e.value! as Map<String, Object?>)},",
    );
  }
  b
    ..writeln('      };')
    ..writeln()
    ..writeln(
      '  // ---- idle ambient motion -----------------------------------------------',
    );
  // Fields that count whole milliseconds stay int (for Duration(milliseconds:
  // …)); every other idle/lipsync number is a double so seconds-based math
  // (periods, phases) never hits a static int/double mismatch, regardless of
  // whether avatar.json happens to spell the value without a decimal point.
  const msFields = <String>{'blinkMs', 'attackMs', 'releaseMs'};
  for (final e in idle.entries) {
    final v = e.value;
    if (v is List<Object?>) {
      final nums = v.map((e) => (e! as num).toDouble()).join(', ');
      b
        ..writeln('  /// `${e.key}` from avatar.json.')
        ..writeln('  static const List<double> ${e.key} = <double>[$nums];');
    } else if (msFields.contains(e.key)) {
      b
        ..writeln('  /// `${e.key}` from avatar.json.')
        ..writeln('  static const int ${e.key} = ${(v! as num).toInt()};');
    } else {
      b
        ..writeln('  /// `${e.key}` from avatar.json.')
        ..writeln(
          '  static const double ${e.key} = ${(v! as num).toDouble()};',
        );
    }
  }
  final transitionMs = (transition['moodMs']! as num).toInt();
  final transitionCurve = transition['curve']! as String;
  b
    ..writeln()
    ..writeln(
      '  // ---- mood transition ----------------------------------------------------',
    )
    ..writeln('  /// `transition.moodMs` from avatar.json.')
    ..writeln('  static const int transitionMs = $transitionMs;')
    ..writeln('  /// `transition.curve` from avatar.json.')
    ..writeln('  static const Curve transitionCurve = Curves.$transitionCurve;')
    ..writeln()
    ..writeln(
      '  // ---- lip-sync envelope --------------------------------------------------',
    );
  for (final e in lipsync.entries) {
    final v = e.value;
    if (msFields.contains(e.key)) {
      b
        ..writeln('  /// `${e.key}` from avatar.json.')
        ..writeln('  static const int ${e.key} = ${(v! as num).toInt()};');
    } else {
      b
        ..writeln('  /// `${e.key}` from avatar.json.')
        ..writeln(
          '  static const double ${e.key} = ${(v! as num).toDouble()};',
        );
    }
  }
  b
    ..writeln()
    ..writeln(
      '  // ---- default client-side mood rules (D83) ------------------------------',
    )
    ..writeln(
      '  /// `rules.default` from avatar.json: `(on, mood, ttlMs)`.\n'
      '  /// `ttlMs == 0` means "until the next change".',
    )
    ..writeln(
      '  static const List<(String on, String mood, int ttlMs)> defaultRules =',
    )
    ..writeln('      <(String, String, int)>[');
  for (final r in rules) {
    final m = r! as Map<String, Object?>;
    final on = m['on']! as String;
    final mood = m['mood']! as String;
    final ttlMs = (m['ttlMs']! as num).toInt();
    b.writeln("        ('$on', '$mood', $ttlMs),");
  }
  b
    ..writeln('      ];')
    ..writeln('}');

  final content = b.toString();
  if (check) {
    final tmp = File('${Directory.systemTemp.path}/kletso_avatar_check.dart')
      ..writeAsStringSync(content);
    Process.runSync('dart', ['format', tmp.path]);
    final formatted = tmp.readAsStringSync();
    tmp.deleteSync();
    if (!out.existsSync() || out.readAsStringSync() != formatted) {
      stderr.writeln(
        'kletso_avatar_face.g.dart is out of date; run '
        'dart run tool/gen_avatar.dart',
      );
      exitCode = 1;
      return;
    }
    stdout.writeln('kletso_avatar_face.g.dart up to date');
    return;
  }
  out.writeAsStringSync(content);
  Process.runSync('dart', ['format', out.path]);
  stdout.writeln('wrote ${out.path}');
}
