include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    unawaited_futures: error
    discarded_futures: error
    empty_catches: error
    avoid_dynamic_calls: error
    always_declare_return_types: error
    cancel_subscriptions: error
    close_sinks: error
    exhaustive_cases: error
    avoid_print: error
    public_member_api_docs: warning

linter:
  rules:
    public_member_api_docs: true
    always_declare_return_types: true
    type_annotate_public_apis: true
    avoid_dynamic_calls: true
    prefer_final_locals: true
    prefer_single_quotes: true
    cancel_subscriptions: true
    close_sinks: true
    unawaited_futures: true
    discarded_futures: true
    avoid_print: true
    avoid_positional_boolean_parameters: true
    directives_ordering: true
    prefer_relative_imports: true
    sort_pub_dependencies: true
    unnecessary_breaks: true
    require_trailing_commas: true
    use_super_parameters: true
    exhaustive_cases: true
