// GENERATED by tool/gen_tokens.dart from packages/design/tokens.json.
// Do not edit; run `dart run tool/gen_tokens.dart`.

import 'package:flutter/painting.dart';

/// Primitive Kletso design tokens (raw values). Widgets never use these
/// directly; they read semantic roles from `KletsoTheme`.
abstract final class KletsoTokens {
  // ---- colour --------------------------------------------------------------
  /// `#FF6A2B`.
  static const Color dutchOrange = Color(0xFFFF6A2B);

  /// `#E55A1F`.
  static const Color orangeDark = Color(0xFFE55A1F);

  /// `#1E2A44`.
  static const Color deepNavy = Color(0xFF1E2A44);

  /// `#364563`.
  static const Color navyLight = Color(0xFF364563);

  /// `#FBF7F0`.
  static const Color cream = Color(0xFFFBF7F0);

  /// `#B8F0DC`.
  static const Color softMint = Color(0xFFB8F0DC);

  /// `#FFE08A`.
  static const Color butterYellow = Color(0xFFFFE08A);

  /// `#111827`.
  static const Color gray900 = Color(0xFF111827);

  /// `#6B7280`.
  static const Color gray600 = Color(0xFF6B7280);

  /// `#E5E7EB`.
  static const Color gray200 = Color(0xFFE5E7EB);

  /// `#22C55E`.
  static const Color green = Color(0xFF22C55E);

  /// `#EF4444`.
  static const Color red = Color(0xFFEF4444);

  /// `#3B82F6`.
  static const Color blue = Color(0xFF3B82F6);

  /// `#FFFFFF`.
  static const Color paper = Color(0xFFFFFFFF);

  /// `#FFB48F`.
  static const Color orange300 = Color(0xFFFFB48F);

  /// `#FFE4D5`.
  static const Color orange100 = Color(0xFFFFE4D5);

  /// `#FFF1E8`.
  static const Color orange50 = Color(0xFFFFF1E8);

  /// `#DCE1EC`.
  static const Color navy100 = Color(0xFFDCE1EC);

  /// `#DBEAFE`.
  static const Color blue100 = Color(0xFFDBEAFE);

  /// `#2BB39A`.
  static const Color teal = Color(0xFF2BB39A);

  /// `#F5A623`.
  static const Color amber = Color(0xFFF5A623);

  /// `#F1E8DC`.
  static const Color lineOnCream = Color(0xFFF1E8DC);

  /// `#FFF6EC`.
  static const Color cream2 = Color(0xFFFFF6EC);

  // ---- typography ----------------------------------------------------------
  /// Primary UI font family.
  static const String fontFamily = 'Plus Jakarta Sans';

  /// Handwritten accent family (marketing only).
  static const String fontFamilyHand = 'Caveat';

  /// Marketing scale `h1`: 72/80 weight 700.
  static const double fontH1Size = 72;

  /// Line height of `h1`.
  static const double fontH1LineHeight = 80;

  /// Weight of `h1`.
  static const FontWeight fontH1Weight = FontWeight.w700;

  /// Marketing scale `h2`: 40/48 weight 700.
  static const double fontH2Size = 40;

  /// Line height of `h2`.
  static const double fontH2LineHeight = 48;

  /// Weight of `h2`.
  static const FontWeight fontH2Weight = FontWeight.w700;

  /// Marketing scale `h3`: 28/36 weight 600.
  static const double fontH3Size = 28;

  /// Line height of `h3`.
  static const double fontH3LineHeight = 36;

  /// Weight of `h3`.
  static const FontWeight fontH3Weight = FontWeight.w600;

  /// Marketing scale `h4`: 20/28 weight 600.
  static const double fontH4Size = 20;

  /// Line height of `h4`.
  static const double fontH4LineHeight = 28;

  /// Weight of `h4`.
  static const FontWeight fontH4Weight = FontWeight.w600;

  /// Marketing scale `bodyLarge`: 18/28 weight 400.
  static const double fontBodyLargeSize = 18;

  /// Line height of `bodyLarge`.
  static const double fontBodyLargeLineHeight = 28;

  /// Weight of `bodyLarge`.
  static const FontWeight fontBodyLargeWeight = FontWeight.w400;

  /// Marketing scale `body`: 16/24 weight 400.
  static const double fontBodySize = 16;

  /// Line height of `body`.
  static const double fontBodyLineHeight = 24;

  /// Weight of `body`.
  static const FontWeight fontBodyWeight = FontWeight.w400;

  /// Marketing scale `small`: 14/20 weight 400.
  static const double fontSmallSize = 14;

  /// Line height of `small`.
  static const double fontSmallLineHeight = 20;

  /// Weight of `small`.
  static const FontWeight fontSmallWeight = FontWeight.w400;

  /// Marketing scale `caption`: 12/16 weight 400.
  static const double fontCaptionSize = 12;

  /// Line height of `caption`.
  static const double fontCaptionLineHeight = 16;

  /// Weight of `caption`.
  static const FontWeight fontCaptionWeight = FontWeight.w400;

  // ---- radius --------------------------------------------------------------
  /// Radius `sm`.
  static const double radiusSm = 8;

  /// Radius `md`.
  static const double radiusMd = 12;

  /// Radius `lg`.
  static const double radiusLg = 16;

  /// Radius `xl`.
  static const double radiusXl = 24;

  /// Radius `pill`.
  static const double radiusPill = 999;

  // ---- spacing -------------------------------------------------------------
  /// Spacing steps in logical pixels.
  static const List<double> spacing = <double>[
    4,
    8,
    12,
    16,
    20,
    24,
    32,
    40,
    48,
    64,
    80,
    96,
  ];

  /// Max content width on large screens.
  static const double container = 1200;
}
