// GENERATED by tool/gen_avatar.dart from packages/design/avatar.json.
// Do not edit; run `dart run tool/gen_avatar.dart`.

import 'package:flutter/animation.dart' show Curve, Curves;
import 'package:flutter/painting.dart' show Color, Offset;

/// Raw mascot face data parsed from `packages/design/avatar.json`
/// (D81). [KletsoAvatarFaceParams.forMood] and
/// [KletsoAvatarController] build on this; widgets never read it
/// directly.
abstract final class KletsoAvatarFaceData {
  // ---- colours ---------------------------------------------------------
  /// `#FF6A2B` (`body` in avatar.json).
  static const Color bodyColor = Color(0xFFFF6A2B);

  /// `#FF9A6B` (`bodyHighlight` in avatar.json).
  static const Color bodyHighlight = Color(0xFFFF9A6B);

  /// `#D9531F` (`bodyShadow` in avatar.json).
  static const Color bodyShadow = Color(0xFFD9531F);

  /// `#1E2A44` (`eye` in avatar.json).
  static const Color eyeColor = Color(0xFF1E2A44);

  /// `#FFFFFF` (`eyeGloss` in avatar.json).
  static const Color eyeGloss = Color(0xFFFFFFFF);

  /// `#1E2A44` (`mouth` in avatar.json).
  static const Color mouthColor = Color(0xFF1E2A44);

  /// `#FF5C8A` (`tongue` in avatar.json).
  static const Color tongueColor = Color(0xFFFF5C8A);

  /// `#FFFFFF` (`teeth` in avatar.json).
  static const Color teethColor = Color(0xFFFFFFFF);

  /// `#FF8F6B` (`blush` in avatar.json).
  static const Color blushColor = Color(0xFFFF8F6B);

  // ---- geometry (face units; head = circle radius 1 at (0,0)) -----------
  /// `eyeCenterX` from avatar.json.
  static const double eyeCenterX = 0.3;

  /// `eyeCenterY` from avatar.json.
  static const double eyeCenterY = -0.12;

  /// `eyeRadius` from avatar.json.
  static const double eyeRadius = 0.15;

  /// `eyeGlossRadius` from avatar.json.
  static const double eyeGlossRadius = 0.045;

  /// `eyeGlossOffset` from avatar.json.
  static const Offset eyeGlossOffset = Offset(-0.04, -0.045);

  /// `arcEyeStroke` from avatar.json.
  static const double arcEyeStroke = 0.07;

  /// `gazeTravel` from avatar.json.
  static const double gazeTravel = 0.12;

  /// `eyeTiltTravel` from avatar.json.
  static const double eyeTiltTravel = 0.16;

  /// `mouthCenterY` from avatar.json.
  static const double mouthCenterY = 0.3;

  /// `mouthCurveTravel` from avatar.json.
  static const double mouthCurveTravel = 0.16;

  /// `mouthOpenTravel` from avatar.json.
  static const double mouthOpenTravel = 0.65;

  /// `lipStroke` from avatar.json.
  static const double lipStroke = 0.045;

  /// `tongueWidth` from avatar.json.
  static const double tongueWidth = 0.55;

  /// `tongueHeight` from avatar.json.
  static const double tongueHeight = 0.5;

  /// `teethHeight` from avatar.json.
  static const double teethHeight = 0.22;

  /// `blushCenter` from avatar.json.
  static const Offset blushCenter = Offset(0.62, 0.18);

  /// `blushRadius` from avatar.json.
  static const double blushRadius = 0.14;

  /// `bounceTravel` from avatar.json.
  static const double bounceTravel = 0.06;

  // ---- defaults: the neutral baseline every mood overrides from ---------
  /// `defaults` from avatar.json.
  static const Map<String, Object?> defaults = <String, Object?>{
    'eyeOpen': 1.0,
    'eyeShape': 'round',
    'winkRight': false,
    'gaze': <double>[0.0, 0.0],
    'eyeTilt': 0.0,
    'mouthCurve': 0.35,
    'mouthOpen': 0.42,
    'mouthWidth': 0.45,
    'tongue': 0.2,
    'teeth': 0.0,
    'blush': 0.0,
    'headTilt': 0.0,
    'bounce': 0.0,
  };

  // ---- moods: only the params each mood changes --------------------------
  /// `moods` from avatar.json, keyed by the wire mood name.
  static const Map<String, Map<String, Object?>> moods =
      <String, Map<String, Object?>>{
        'neutral': <String, Object?>{},
        'happy': <String, Object?>{
          'mouthCurve': 0.8,
          'mouthOpen': 0.7,
          'mouthWidth': 0.58,
          'tongue': 0.45,
          'blush': 0.5,
        },
        'laughing': <String, Object?>{
          'eyeOpen': 0.0,
          'eyeShape': 'arc',
          'mouthCurve': 0.9,
          'mouthOpen': 0.85,
          'mouthWidth': 0.65,
          'tongue': 0.5,
          'teeth': 1.0,
          'bounce': 1.0,
          'blush': 0.6,
        },
        'surprised': <String, Object?>{
          'eyeOpen': 1.2,
          'mouthCurve': 0.0,
          'mouthOpen': 0.6,
          'mouthWidth': 0.3,
          'tongue': 0.3,
        },
        'thinking': <String, Object?>{
          'eyeOpen': 0.9,
          'gaze': <double>[0.3, -0.4],
          'eyeTilt': 0.6,
          'mouthCurve': -0.1,
          'mouthOpen': 0.05,
          'mouthWidth': 0.3,
          'headTilt': -4.0,
        },
        'wink': <String, Object?>{
          'winkRight': true,
          'mouthCurve': 0.7,
          'mouthOpen': 0.55,
          'mouthWidth': 0.52,
          'tongue': 0.35,
        },
        'listening': <String, Object?>{
          'eyeOpen': 1.05,
          'gaze': <double>[0.0, 0.1],
          'mouthCurve': 0.3,
          'mouthOpen': 0.05,
          'mouthWidth': 0.4,
          'headTilt': 3.0,
        },
        'speaking': <String, Object?>{
          'mouthCurve': 0.5,
          'mouthOpen': 'lipsync',
          'mouthWidth': 0.62,
          'tongue': 0.3,
        },
        'sorry': <String, Object?>{
          'eyeOpen': 0.8,
          'eyeTilt': -0.5,
          'mouthCurve': -0.4,
          'mouthOpen': 0.08,
          'mouthWidth': 0.35,
        },
        'confused': <String, Object?>{
          'gaze': <double>[-0.3, -0.2],
          'eyeTilt': 0.7,
          'mouthCurve': -0.1,
          'mouthOpen': 0.08,
          'mouthWidth': 0.25,
          'headTilt': 6.0,
        },
        'sleepy': <String, Object?>{
          'eyeOpen': 0.25,
          'mouthCurve': 0.2,
          'mouthOpen': 0.08,
          'mouthWidth': 0.35,
          'bounce': -1.0,
        },
      };

  // ---- idle ambient motion -----------------------------------------------
  /// `breathScale` from avatar.json.
  static const double breathScale = 0.02;

  /// `breathSeconds` from avatar.json.
  static const double breathSeconds = 3.2;

  /// `blinkEverySeconds` from avatar.json.
  static const List<double> blinkEverySeconds = <double>[3.0, 6.0];

  /// `blinkMs` from avatar.json.
  static const int blinkMs = 120;

  /// `gazeDriftSeconds` from avatar.json.
  static const double gazeDriftSeconds = 5.0;

  /// `gazeDriftAmount` from avatar.json.
  static const double gazeDriftAmount = 0.35;

  /// `bounceSeconds` from avatar.json.
  static const double bounceSeconds = 0.6;

  // ---- mood transition ----------------------------------------------------
  /// `transition.moodMs` from avatar.json.
  static const int transitionMs = 220;

  /// `transition.curve` from avatar.json.
  static const Curve transitionCurve = Curves.easeOutCubic;

  // ---- lip-sync envelope --------------------------------------------------
  /// `attackMs` from avatar.json.
  static const int attackMs = 30;

  /// `releaseMs` from avatar.json.
  static const int releaseMs = 120;

  /// `minOpen` from avatar.json.
  static const double minOpen = 0.05;

  /// `maxOpen` from avatar.json.
  static const double maxOpen = 0.85;

  /// `gain` from avatar.json.
  static const double gain = 2.5;

  // ---- default client-side mood rules (D83) ------------------------------
  /// `rules.default` from avatar.json: `(on, mood, ttlMs)`.
  /// `ttlMs == 0` means "until the next change".
  static const List<(String on, String mood, int ttlMs)> defaultRules =
      <(String, String, int)>[
        ('agent.typing', 'thinking', 0),
        ('tool.started', 'thinking', 0),
        ('tool.failed', 'sorry', 2500),
        ('error', 'sorry', 2500),
        ('message.completed', 'happy', 2000),
        ('voice.listening', 'listening', 0),
        ('voice.thinking', 'thinking', 0),
        ('voice.speaking', 'speaking', 0),
        ('voice.idle', 'neutral', 0),
        ('unread', 'wink', 1500),
        ('handoff.started', 'neutral', 0),
      ];
}
